[package]
name = "user"
version = "0.1.0"
edition = "2024"

[lib]
test = false
doctest = false
bench = false

[[bin]]
name = "shell"
test = false
doctest = false
bench = false

[dependencies]
common = { workspace = true }
